<?php

return array (
  'name' => '银客帮',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'general/profile',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'dictionary' => 'Dictionary',
    'site' => 'Site',
    'withdraw' => 'Withdraw',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'is_open_agent_reward' => '1',
  'draw_start_time' => '0',
  'draw_end_time' => '24',
  'draw_rate' => '0',
  'draw_num' => '5',
  'draw_mult_money' => '2',
  'is_open_level_reward' => '1',
  'update_every_time' => '1',
  'meal_list_ad' => '/uploads/20200416/2644ee2c4fd945a2.jpg',
  'service_phone' => '',
  'service_image' => '',
  'about' => '<p>银客帮任务分发平台</p><p><br></p>',
  'registration_protocol' => '<ul><li style="text-align: center;"><span style="font-size: 24px;">﻿</span><b><span style="font-size: 24px;">注册协议</span></b></li><li style="text-align: center;"><ul><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">一、注册条款的接受</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">请您认真阅读本协议尤其是免除或者限制本平台责任的条款及其它限制您权利的条款，一旦您注册即表示您已经阅读并且同意与本平台达成协议，完全理解并接受所有的注册条款。阅读本协议过程中，如果您不同意本协议或其中任何条款约定，您应立即停止注册程序。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">二 、用户注册条件</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">1. 申请注册成为本平台的用户应同时满足下列全部条件： 在注册之日以及此后使用本平台服务期间必须为短视频平台服务为目的； 在注册之日必须年满18周岁以上。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">2. 为更好的享有本平台提供的服务，用户应： 向本平台提供本人真实、正确、最新及完整的资料； 随时更新登记资料，保持其真实性及有效性； 提供真实有效的联系人手机号码；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">3. 若用户提供任何错误、不实或不完整的资料，或本平台有理由怀疑资料为错误、不实或不完整及违反用户注册条款的，或本平台有理由怀疑其用户资料、言行等有悖于“广告”主题的，本平台有权修改用户的注册昵称等，或暂停或终止该用户的帐号，或暂停或终止提供本平台提供的全部或部分服务。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;;">任何注册和使用的本平台账号名称，不得有下列情形：</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（一）违反宪法或法律法规规定的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（二）危害国家安全，泄露国家秘密，颠覆国家政权，破坏国家统一的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（三）损害国家荣誉和利益的，损害公共利益的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（四）煽动民族仇恨、民族歧视，破坏民族团结的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（五）破坏国家宗教政策，宣扬邪教和封建迷信的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（六）散布谣言，扰乱社会秩序，破坏社会稳定的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（七）散布淫秽、色情、赌博、暴力、凶杀、恐怖或者教唆犯罪的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（八）侮辱或者诽谤他人，侵害他人合法权益的；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">（九）含有法律、行政法规禁止的其他内容的。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">用户以虚假信息骗取账号名称注册，或其账号头像、简介等注册信息存在违法和不良信息的，本平台有权采取通知限期改正、暂停使用、注销登记等措施。 对冒用关联机构或社会名人注册账号名称的用户，本平台有权注销其账号。用户应采取适当措施保障注册用户名和密码的机密性并对以其用户名和密码进行的所有活动承担全部责任。用户应确保于每次会话结束后退出帐户，若发现未经授权使用其用户名或密码或其他侵犯其帐户安全的任何行为立即通知本平台；本平台对未遵守上述规定而给用户或他人带来的任何损失不承担责任。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">三、用户个人信息保护</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">1、本平台非常重视您的个人信息保护，保证在合法、正当与必要的原则下收集、使用或者公开您的个人信息且不会收集与提供和本产品服务无关的个人信息。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">2、您在注册帐号或使用本服务的过程中，为了更好地向您提供相关服务，本平台可能需要您填写或提交一些必要的基础个人信息，如法律法规、规章规范性文件（以下称“法律法规”）规定的需要填写的身份信息。如您提交的信息不完整或不符合法律法规的规定，则您可能无法使用本服务或在使用本服务的过程中受到限制。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">3、本平台收集的用户个人信息包括：1）用户在注册时需自行提供的必要个人信息（如注册时填写的手机号码、性别、年龄等个人信息等）；2）本平台为提供服务过程中合法收集的用户个人信息，如用户使用服务时的设备信息、账号信息、日志信息、个人基本资料、好友信息等。请注意，单独的设备信息、日志信息等是无法识别特定自然人身份的信息；具体用途如下：</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">(1) 本平台向用户及时发送重要通知，如软件更新、本协议条款的变更；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">(2) 本平台内部进行审计、数据分析和研究等，以改进本平台的产品、服务和与用户之间的沟通；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">(3) 依本协议约定，本平台提供相关服务、管理、审查用户信息及进行处理措施；</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">(4) 适用法律法规规定的其他事项。 除上述事项外，如未取得用户事先同意，本平台不会将用户个人信息使用于任何其他用途。如果本平台将您的个人信息用于任何未载明的其他用途，或者将基于特定目的收集而来的信息用于其他目的时，会事先征求您的同意。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">4、尊重个人信息的私有性是本平台的一贯制度，本平台将采取技术措施和其他必要措施，确保用户个人信息安全，防止在本服务中收集的用户个人信息泄露、毁损或丢失。在发生前述情形或者本平台发现存在发生前述情形的可能时，本平台将及时采取补救措施并告知用户，用户如发现存在前述情形亦需立即与本平台联系。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">5、本平台重视对未成年人的保护。本平台将依赖用户提供的个人信息判断用户是否为未成年人。任何18岁以下的未成年人均不得注册帐号或使用本服务。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">6、本平台十分注重保护用户的个人信息，并单独制定了《隐私政策》，用户可在注册用户时查看，亦可通过“我”—“设置”—“关于我们”页面里的“隐私政策”来进行查看，用户确认并同意使用本平台提供的服务将被视为接受《隐私政策》。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">四、免责及责任限制条款</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">1、本平台不保证所提供的服务一定能满足您的要求和期望，也不保证服务不会中断，对服务的及时性、安全性、准确性都不作保证。如果系统发生故障、进行维护或维修或其他超出我们控制的原因，导致对本平台的访问暂时中止或错误，本平台可能无法事先通知，用户同意在此情况下对造成任何的损失（如有）免除本平台的任何责任。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">2、对于您通过本平台提供的服务传送的内容，本平台会尽合理努力按照国家有关规定严格审查，但无法完全控制经由网站服务传送的内容，不保证内容的正确性、完整性或品质。因此用户在使用本平台服务时，可能会接触到令人不快、不适当或令人厌恶的内容。在任何情况下，本平台均不为用户经由网站服务以张贴、发送电子邮件或其它方式传送的任何内容负责。但本平台有权依法停止传输任何前述内容并采取相应行动，包括但不限于暂停用户使用网站服务的全部或部分，保存有关记录，并根据国家法律法规、相关政策在必要时向有关机关报告并配合有关机关的行动。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">3、对于本平台提供的各种广告信息、链接、资讯等，本平台会对广告内容进行初步审核，但是本平台难以确保对方产品真实性、合法性或可靠性，由于产品购买导致的相关责任主要由广告商承担；敬告用户理性看待，如需购买或者交易，请谨慎考虑。并且，对于用户经由本平台服务与广告商进行联系或商业往来，完全属于用户和广告商之间的行为，与本平台无关。对于前述商业往来所产生的任何损害或损失，本平台不承担任何责任。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">4、对于用户上传的照片、资料、证件等，本平台已采用相关措施并已尽合理努力进行审核，但无法完全保证其内容的正确性、合法性或可靠性，相关责任由上传上述内容的用户负责，本平台不承担任何责任。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">5、您应以自己的独立判断从事与交友相关的行为，并独立承担可能产生的不利后果和责任，本平台不承担任何法律责任。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">6、依据有关法律法规的规定或依据行政机关、司法机关、检察机关的要求，向其提供用户的基本信息或站内聊天信息，上述行为侵犯用户隐私权的，本平台不承担任何法律责任。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">7、本平台作为交友平台，帮助用户寻找心仪伴侣是我们的服务内容。本平台推出的缘分小助手、有缘红娘、收信宝等服务，全都是在用户同意并主动授权的情况下帮助授权用户寻找异性的功能性服务。本平台不能保证用户通过此类服务授权由系统自动发出或接收到的信息完全满足用户交友需求。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">缘分小助手，为了提高用户处理私信的能力，看到更多符合自己要求的异性来信，提供了有缘小助手服务。在用户主动授权设置有缘小助手的情况下，有缘小助手会帮助用户过滤掉信箱中异性发来的招呼类信件，此类过滤掉的私信只是设为已读，仍然存于授权用户的信箱中。过滤的同时给符合授权用户征友要求的异性发送本平台系统自动做出的信件回复。回复内容由本平台根据用户交友互动中最常用的词语拟定，并由系统随机选取后发送。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">有缘红娘，为了帮助女用户找到符合自己要求的异性，提供了有缘红娘服务。有缘红娘服务内容包括：优先将红娘用户推荐给优质男性用户，获得更多交流机会；有缘红娘将帮助申请有缘红娘服务的用户向符合其征友要求的异性询问交友意向；实时监控询问总数。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">收信宝，为了帮助男用户找到符合自己要求的异性，提供了收信宝服务。收信宝服务内容包括：优先将收信宝用户展示给女用户，通过替男用户打招呼的方式向符合男用户征友要求的女用户介绍男用户，从而增加男用户收信。 以上三种服务用户可以自行取消。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">8、本平台为了促进用户互动，产品上的组件应用或小游戏可能带有触发招呼的功能。用户在玩此功能的组件或小游戏的同时会给符合自己征友要求的异性发去问候招呼。本平台不能保证用户通过此类组件或小游戏发出或接受到的信息完全满足用户的交友需求。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">9、本平台对于用户或任何第三人因使用本平台可能导致的任何金钱或其他损失或损害不承担任何责任（该等损失或损害包括但不限于，任何直接的、间接的、惩罚性的或必然的损失或伤害，或任何收入、利润、信誉、数据、合同、资金使用上的任何损失，或以任何方式由任何种类的业务中断引起或与之相关的损失或伤害，无论是民事侵权行为、合同还是其他）。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">10、用户因任何其他第三方（包括但不限于自然人）使用本平台引起的行为，向第三方要求索赔或进行诉讼，用户同意独自进行该类索赔或诉讼，不会要求本平台协助举证或者将本平台列为被告，而且同意豁免本平台承担由该索赔或诉讼引起的任何相关联的所有索赔、责任和损失。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">11、您理解并同意本平台仅仅是为您和其他用户的交往提供平台，但对用户间的来往（无论是在网上或在现实生活中），用户须对自己的行为承担全部责任。如您与其他用户产生争议，则理解并同意本平台并没有义务监控或处理用户之间的争议。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">五、用户应遵守以下法律法规：</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">1、本平台提醒用户在使用本平台服务时，遵守《中华人民共和国合同法》、《中华人民共和国著作权法》、《全国人民代表大会常务委员会关于维护互联网安全的决定》、《中华人民共和国保守国家秘密法》、《中华人民共和国电信条例》、《中华人民共和国计算机信息系统安全保护条例》、《中华人民共和国计算机信息网络国际联网管理暂行规定》及其实施办法、《计算机信息系统国际联网保密管理规定》、《互联网信息服务管理办法》、《计算机信息网络国际联网安全保护管理办法》、《互联网电子公告服务管理规定》、《互联网用户账号名称管理规定》等相关中国法律法规的规定。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">2、在任何情况下，如果本平台有理由认为用户使用本平台服务过程中的任何行为，包括但不限于用户的任何言论和其它行为违反或可能违反上述法律和法规的任何规定，本平台可在任何时候不经任何事先通知终止向该用户提供服务。</li><li style="margin: 10px 0px; color: rgb(0, 0, 0); font-family: &quot;PingFang SC&quot;; font-size: medium;"><span style="font-size: 14px;">六、法律适用与争议管辖</span></li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">1、本协议之订立、生效、解释、修订、补充、终止、执行与争议解决均适用于中华人民共和国大陆地区法律。</li><li style="font-family: &quot;PingFang SC&quot;; font-size: 0.8rem;">2、用户与本平台就本协议内容或其执行发生任何争议，应进行友好协商；协商不成时，任何一方均可向被告经营地有管辖权的人民法院提起诉讼。</li></ul></li></ul>',
  'wap_url' => 'http://116.211.148.34:11000',
  'app_update_note' => '更新app',
  'app_update_url' => 'http://116.211.148.34:11000',
  'app_version' => '3.0.0',
  'can_apply_task' => '1',
  'no_apply_task_remark' => '系统升级中，暂停该功能',
  'pay_appid' => '',
  'pay_private_key' => '',
  'pay_url' => 'http://www.baidu.com',
  'app_down_url' => 'https://www.baidu.com/',
  'regsite_send_amount' => '1.00',
  'max_meal_ids' => '1,2,3,4',
);